### ISSUE TITLE
site issue

### ISSUE THREAD

**Issue by nerdralph** [karldiab/EthereumMiningCalculator#3]
On your page you say mining will end this summer.  The exponential difficulty growth be delayed until 2017, as the proof of stake code (in Serenity) will not be ready for mainstream until then.
https://blog.ethereum.org/2015/03/03/ethereum-launch-process/

**Comment by karldiab** [comment]
Still can't see any clear indication of when the difficulty bomb will come into play, but I'll remove that bit of info anyway

**Comment by nerdralph** [comment]
It takes a bit of work to piece together all the information, but recently
Vitalik made a clear statement saying it will be delayed.
https://docs.google.com/presentation/d/1JKKef7NVjgtRZFsTcAteS4VtHG0aYu7TApZhWUENbWQ/edit?pref=2&pli=1#slide=id.g11fae5a2e1_0_68
